server:
  port: 9100

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: CART-SERVICE
          uri: lb://CART-SERVICE
          predicates:
            - Path=/cart/**

        - id: LOCATION-SERVICE
          uri: lb://LOCATION-SERVICE
          predicates:
            - Path=/location/**
          filters:
            - name: CircuitBreaker
              args:
                name: LOCATION-SERVICE
                fallbackuri: forward:/locationServiceFallback
        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
          filters:
            - name: CircuitBreaker
              args:
                name: PAYMENT-SERVICE
                fallbackuri: forward:/paymentServiceFallback
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
          filters:
            - name: CircuitBreaker
              args:
                name: USER-SERVICE
                fallbackuri: forward:/userServiceFallback
        - id: ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
          filters:
            - name: CircuitBreaker
              args:
                name: ORDER-SERVICE
                fallbackuri: forward:/orderServiceFallback


hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost